image: "node:latest"

stages:
- build
- deploy

build_app:
  stage: build
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
    - .next
    expire_in: 1 day

deploy_draft:
  stage: deploy
  only:
  - main
  script:
  - npm install -g netlify-cli
  - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_TOKEN} --dir .next

deploy_prod:
  stage: deploy
  only:
  - main
  script:
  - npm install -g netlify-cli
  - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_TOKEN} --dir .next --prod
  when: manual